[project]
name = "simple-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=1.3.0",
    "mcp[cli]>=1.20.0",
    "yfinance>=0.2.66",
]
